// 学霸笔记 · 展示数据（真实转换结果）
// 仅用于首页案例展示，「我的教程」页面从用户自己的转换记录读取

const SAMPLE_TUTORIALS = [
  {
    id: 't001',
    title: '10分钟学会24个 Claude Code 使用技巧',
    cover: 'gradient-1',
    author: 'NexAI 奈势学城',
    authorAvatar: 'NA',
    sourceUrl: 'https://www.bilibili.com/video/BV1SddcBFESs/',
    duration: '12:21',
    durationSec: 741,
    views: '18.6万',
    createdAt: '2026-05-24',
    status: 'done',
    starred: true,
    tags: ['Claude Code', 'AI编程', '效率工具'],
    keypointCount: 35,
    overview: '《10分钟学会24个ClaudeCode使用技巧》是一条面向AI开发与编程辅助工具使用者的高效教程视频。通过24个关键知识点，系统讲解了ClaudeCode的核心操作与进阶功能，包括如何发起请求与理解计划模式、利用回滚与终端模式高效调试、调整思考强度以优化输出，以及通过Skills、Agents和插件扩展AI能力。适合希望在短时间内从基础操作到高阶应用全面掌握这一工具的开发者。',
    keypoints: [
      { idx: 1, ts: 26, tsStr: '00:00:26', title: '发起首个请求',
        summary: '输入请求，让ClaudeCode开始工作，进入计划模式。',
        coreBullets: ['项目启动前需先创建**空项目文件夹**，在地址栏输入 `cmd` 快速调出终端', 'Claude Code 启动命令为 `claude`，首次打开需信任当前目录', '直接输入自然语言需求（如"帮我做一个摄影师的个人网站"）回车即可发起任务'],
        detail: '在**空目录**下发起新项目请求时，Claude Code 会自动进入**计划模式**，优先生成项目架构方案，等待用户确认后再开始实际编写代码。这一机制避免了 AI 直接动手导致方向偏差，适合从零开始的新项目。',
        notes: '', frames: 2,
      },
      { idx: 2, ts: 34, tsStr: '00:00:34', title: '计划模式解释',
        summary: '讲解计划模式功能：AI会生成计划并暂停，等待用户批准。',
        coreBullets: ['触发场景：向空项目目录下发开发类需求时，工具会**自动进入计划模式**', '可通过命令行左下角的`plan mode on`标识确认当前处于计划模式', '审批选项：自动同意后续编辑 / 手动确认每步 / 继续讨论'],
        detail: '状态切换：按 `shift+tab` 可在计划模式和正常模式之间切换，按 `esc` 可随时中断当前执行流程。\n\n三种审批粒度适合不同场景：**自动同意**适合对方向有把握时快速推进；**手动确认**适合每步都需审查的精细场景；**继续讨论**用于方案还需调整时。',
        notes: '', frames: 2,
      },
      { idx: 3, ts: 96, tsStr: '00:01:36', title: '回滚功能介绍',
        summary: '介绍使用回滚命令（或ESC键）撤销不满意的更改。',
        coreBullets: ['**双击 `Esc` 键**快速进入回滚页面', '支持切换历史节点，恢复到任意历史状态', '提供5种回滚模式：代码+对话 / 仅代码 / 仅对话 / 压缩摘要 / 取消'],
        detail: '回滚的典型使用场景：AI 多次修改后效果越来越差，需要退回到某个"还正常"的历史版本。进入回滚页面后，通过方向键浏览历史节点，找到目标状态后确认，再从5种粒度中选择回滚范围：只回代码、只回对话、两者都回等。',
        notes: '⚠️ 回滚功能仅支持通过 Claude Code 内置工具创建的文件，命令行直接创建的内容无法被回滚。', frames: 2,
      },
      { idx: 4, ts: 200, tsStr: '00:03:20', title: '思考强度调节',
        summary: '通过调整思考强度（快/常规/慢）控制AI的推理深度。',
        coreBullets: ['快速模式：简单任务用，响应快但推理浅', '常规模式：日常开发的默认选择', '慢速/深度思考：复杂架构设计时使用，响应慢但质量高'],
        detail: '切换方式：在输入框前使用 `/think` 命令，或通过快捷键快速切换强度档位。\n\n实用建议：日常开发用常规模式，遇到复杂架构设计、难以复现的 bug、需要权衡多个方案的决策时，切到深度思考模式——虽然响应慢，但分析质量明显更高，减少反复修改的次数。',
        notes: '', frames: 2,
      },
    ],
  },
  {
    id: 't002',
    title: '泛谈 Vibe Coding：用自然语言驱动编程的完整方法论',
    cover: 'gradient-2',
    author: 'NexAI 奈势学城',
    authorAvatar: 'NA',
    sourceUrl: 'https://www.bilibili.com/video/BV1A5LA6sEi4/',
    duration: '41:41',
    durationSec: 2501,
    views: '9.2万',
    createdAt: '2026-05-22',
    status: 'done',
    starred: false,
    tags: ['Vibe Coding', 'AI编程', '方法论'],
    keypointCount: 22,
    overview: '本视频《泛谈Vibe Coding》系统解析这一由Andrej Karpathy提出的前沿编程理念：摆脱传统编程语法束缚，用自然语言描述想法，让AI自动生成代码，实现"会说就能编程"。内容涵盖其定义、技术背景、与AI高效沟通的原则，并详细演示了从需求描述、生成代码、迭代修改到验收部署的完整工作流。',
    keypoints: [],
  },
  {
    id: 't003',
    title: '零基础实战 Codex：从入门到高效 AI 编程伙伴',
    cover: 'gradient-3',
    author: 'NexAI 奈势学城',
    authorAvatar: 'NA',
    sourceUrl: 'https://www.bilibili.com/video/BV1M55v6DELV/',
    duration: '37:30',
    durationSec: 2250,
    views: '15.4万',
    createdAt: '2026-05-21',
    status: 'done',
    starred: false,
    tags: ['Codex', 'AI编程', '零基础'],
    keypointCount: 25,
    overview: '本视频是NexAI奈势学城出品的Codex实战教程，旨在帮助零基础用户快速掌握这一AI驱动的智能编程工具。教程从Codex的核心定义与能力讲起，系统介绍了其安装配置、核心快捷键与命令、关键的安全与权限设置，并重点讲解了提升效率的"Agents.md法则"，通过一个完整塔防游戏实战演示展现完整开发流程。',
    keypoints: [],
  },
  {
    id: 't004',
    title: '零基础如何 Coding 一个自己的网页？完整全流程',
    cover: 'gradient-4',
    author: 'NexAI 奈势学城',
    authorAvatar: 'NA',
    sourceUrl: 'https://www.bilibili.com/video/BV1dY596nEmy/',
    duration: '46:28',
    durationSec: 2788,
    views: '22.1万',
    createdAt: '2026-05-20',
    status: 'done',
    starred: true,
    tags: ['零基础', '建站', 'AI工具'],
    keypointCount: 28,
    overview: '本视频面向零基础、无编程经验的学习者，系统演示了如何借助AI工具从零到一搭建并部署一个功能完整的个人网站。核心在于"用AI替代传统编码"，通过自然语言与AI（豆包、扣子）协作，完成从需求梳理、UI设计到代码生成、功能迭代的全过程。',
    keypoints: [],
  },
  {
    id: 't005',
    title: 'AI 视频从创意到参赛成品：iCan 国一获奖全流程拆解',
    cover: 'gradient-5',
    author: 'NexAI 奈势学城',
    authorAvatar: 'NA',
    sourceUrl: 'https://www.bilibili.com/video/BV1NNoKBYE4F/',
    duration: '24:29',
    durationSec: 1469,
    views: '8.7万',
    createdAt: '2026-05-19',
    status: 'done',
    starred: false,
    tags: ['AI视频', '创作', '比赛'],
    keypointCount: 27,
    overview: '本视频以团队参加iCan创意大赛AI挑战赛并获得国家一等奖的作品《爱连说》为案例，深度剖析AI动画视频从创意构思到参赛成品的完整创作过程。聚焦创作的本质思考，系统讲解了如何通过前期规划、视觉统一和后期打磨，克服AI视频创作中常见的风格混乱、叙事断裂等问题。',
    keypoints: [],
  },
  {
    id: 't006',
    title: 'AI 时代，不要再用岗位定义自己：能力边界重构方法论',
    cover: 'gradient-6',
    author: 'NexAI 奈势学城',
    authorAvatar: 'NA',
    sourceUrl: 'https://www.bilibili.com/video/BV1A5LA6sEi4/',
    duration: '34:04',
    durationSec: 2044,
    views: '11.3万',
    createdAt: '2026-05-18',
    status: 'done',
    starred: false,
    tags: ['AI时代', '职场', '方法论'],
    keypointCount: 19,
    overview: '在AI时代，如何突破岗位限制，快速构建能赚钱的项目能力？本视频并非简单罗列AI工具，而是聚焦于如何将产品、运营与技术能力结合，跑通从想法到商业落地的完整闭环。通过"龙虾BOSS"Agent开发、Goya视频复刻产品、公众号自动化增长三个具体案例，详细演示了如何利用Spike驱动开发与智能体运营等实战技巧。',
    keypoints: [],
  },
];

// 合集探测的模拟数据
const PLAYLIST_PROBE = {
  url: 'https://www.bilibili.com/video/BV1Nx411Q7Bh',
  title: '【合集】Python 高级编程进阶 · 从基础到工程化',
  author: '极客代码课堂',
  authorAvatar: 'JK',
  totalDuration: '8h 24min',
  totalViews: '198.2万',
  cover: 'gradient-3',
  episodes: [
    { idx: 1, title: '环境搭建：pyenv + poetry + ruff 三件套', duration: '18:24', selected: true },
    { idx: 2, title: '装饰器深入：从语法到元编程', duration: '32:18', selected: true },
    { idx: 3, title: '生成器和迭代器：内存友好的数据流', duration: '24:36', selected: true },
    { idx: 4, title: '并发编程：asyncio 实战', duration: '45:12', selected: true },
    { idx: 5, title: '并发进阶：multiprocessing 和 threading', duration: '38:42', selected: true },
    { idx: 6, title: '类型注解：mypy + protocol 工程实践', duration: '28:15', selected: false },
    { idx: 7, title: '面向对象：dataclass、protocol、abc', duration: '34:27', selected: false },
    { idx: 8, title: '测试驱动：pytest + hypothesis', duration: '42:38', selected: false },
    { idx: 9, title: '包管理：从 pip 到 uv 到 monorepo', duration: '31:14', selected: false },
    { idx: 10, title: 'CLI 工具开发：click + rich', duration: '26:48', selected: false },
    { idx: 11, title: 'Web 后端：FastAPI 实战', duration: '52:36', selected: false },
    { idx: 12, title: '数据库：SQLAlchemy 2.0 完整指南', duration: '48:22', selected: false },
    { idx: 13, title: '部署：Docker + uvicorn + nginx', duration: '36:18', selected: false },
    { idx: 14, title: '监控：日志、metrics、tracing', duration: '29:45', selected: false },
  ],
};

// 转换流水线 7 阶段
const PIPELINE_STAGES = [
  { id: 1, name: '解析视频', icon: 'IconLink', desc: '识别链接、获取元信息' },
  { id: 2, name: '下载视频', icon: 'IconDownload', desc: '从B站下载视频文件' },
  { id: 3, name: '提取字幕', icon: 'IconFileText', desc: 'Whisper 语音转文字' },
  { id: 4, name: '分析知识点', icon: 'IconSparkles', desc: 'AI 识别关键时刻' },
  { id: 5, name: '截取关键帧', icon: 'IconImage', desc: '智能截图算法' },
  { id: 6, name: '生成笔记', icon: 'IconWand', desc: 'AI 视觉 + 字幕生成详细笔记' },
  { id: 7, name: '组装教程', icon: 'IconBook', desc: '生成 Markdown / 飞书文档' },
];

// ── 后端地址配置 ────────────────────────────────────────────────────────────────
// 本地开发：留空，前端用相对路径 /api/...
// 线上部署：填入 Railway / Render 等部署地址，如：
//   const BACKEND_URL = 'https://xueba-backend-production.up.railway.app';
const BACKEND_URL = 'https://xueba-backend.onrender.com';

// 演示模式 = 没有配置后端地址 且 不在 localhost
const IS_DEMO_HOST = !BACKEND_URL && (() => {
  const h = window.location.hostname;
  return !h.includes('localhost') && !h.includes('127.0.0.1') && !h.includes('0.0.0.0');
})();

Object.assign(window, { SAMPLE_TUTORIALS, PLAYLIST_PROBE, PIPELINE_STAGES, BACKEND_URL, IS_DEMO_HOST });
